
# coin flip

import random

num_of_flips = 100 #input("How many times do you want to flip a coin? ")
did_it_happen = 0

# flips a coin by the number of flips in "num_of_flips".
def coin_flipper(flips):
    flips_result = []
    for i in range(int(flips)):
        if random.randint(1,2) == 1:
            flips_result.append('H')
        else:
            flips_result.append('T')
    return flips_result

# reads through the list generated by coin_flipper, and tries to identify a streak of 6.
def streak_checker(result):
    heads_streak = 0
    tails_streak = 0
    heads_temp = 0
    tails_temp = 0
    global did_it_happen

    for i in range(len(result)):
        current = result[i]
        if heads_temp == 6:
            heads_temp = 0
            heads_streak +=1
        elif tails_temp == 6:
            tails_temp = 0
            tails_streak += 1
        elif current == 'H':
            heads_temp += 1
            tails_temp = 0
        elif current == 'T':
            tails_temp += 1
            heads_temp = 0

    if heads_streak >= 1 or tails_streak >= 1:
        did_it_happen += 1

# runs both the functions 10000 times to generate a large sample size.
def chance_of_streak(flips):
    for i in range(10000):
        flips_result = coin_flipper(flips)
        streak_checker(flips_result)


chance_of_streak(num_of_flips)
print("The chance of a streak of 6 happening in 100 coin flips is %s" % (did_it_happen / 10000 * 100) + "%")





